name: Django CI/CD

on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry' # Keep this for dependency caching

      - name: Install Poetry
        uses: snok/install-poetry@v1 # Use this action to install Poetry
        with:
          version: 1.x.x # Specify a version or leave empty for latest. e.g., 1.8.2

      - name: Configure Poetry for in-project virtualenvs
        # This step is important for consistent caching and local development
        run: |
          poetry config virtualenvs.in-project true

      - name: Install Dependencies with Poetry
        run: |
          poetry install --no-interaction --no-root

      - name: Run Tests with Poetry
        run: |
          poetry run python manage.py test
